# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='days',
            name='nr_of_tasks',
        ),
        migrations.AlterField(
            model_name='days',
            name='day_date',
            field=models.DateField(verbose_name='Day to plan'),
        ),
        migrations.AddField(
            model_name='daytasks',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScheduleApp.Days'),
        ),
    ]
